apiVersion: rook.io/v1alpha1
kind: Filesystem
metadata:
  name: rookfs
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement:
    resources:
